"""Pydantic request/response models, one module per domain, re-exported here.

The plan lists a single `schemas.py`; it is a package so each domain keeps its own module while
every documented import path (`from kanban.schemas import MoveIn`) still resolves. See CLAUDE.md
section 8. The per-resource modules arrive with their routers, and every public model of each one
is re-exported here so callers never need to know which module declares it.
"""

from kanban.schemas.activity import ActivityPage, BoardActivityOut
from kanban.schemas.archived import ArchivedCardsPage, ArchivedListsPage
from kanban.schemas.attachments import (
    AttachmentCreateIn,
    AttachmentMutated,
    AttachmentOut,
    AttachmentUpdateIn,
    CoverIn,
)
from kanban.schemas.auth import (
    DevLoginIn,
    LoginIn,
    ProfileUpdateIn,
    RegisterIn,
    SessionOut,
    UserListOut,
    UserOut,
)
from kanban.schemas.boards import (
    BackgroundColorOut,
    BackgroundGradientOut,
    BoardBackgroundOut,
    BoardCreateIn,
    BoardGroups,
    BoardOut,
    BoardSummary,
    BoardUpdateIn,
    ClosedBoardGroup,
    CustomBackgroundOut,
    MemberOut,
    MemberRoleIn,
    MembersOut,
    StarOut,
)
from kanban.schemas.cards import (
    CardCopyIn,
    CardCover,
    CardCreateIn,
    CardDetail,
    CardKeepIn,
    CardMoveIn,
    CardMoveResult,
    CardMutated,
    CardsCreated,
    CardSummary,
    CardUpdateIn,
)
from kanban.schemas.checklists import (
    BoardChecklistOut,
    BoardChecklistsOut,
    ChecklistCreateIn,
    ChecklistItemOut,
    ChecklistItemPatchedOut,
    ChecklistMoveResult,
    ChecklistMutated,
    ChecklistOut,
    ChecklistUpdateIn,
    ItemConvertIn,
    ItemCreateIn,
    ItemMoveIn,
    ItemMoveResult,
    ItemMutated,
    ItemPatched,
    ItemsCreated,
    ItemUpdateIn,
)
from kanban.schemas.comments import (
    ActivityFeedItem,
    ActivityOut,
    CardFeedOut,
    CommentCreateIn,
    CommentFeedItem,
    CommentMutated,
    CommentOut,
    CommentUpdateIn,
    FeedItemOut,
)
from kanban.schemas.common import (
    CardBadges,
    CoverKind,
    CoverSize,
    ErrorBody,
    ErrorEnvelope,
    Health,
    LabelColorOut,
    Meta,
    MoveIn,
    MoveResult,
    Mutated,
    PublicUserOut,
)
from kanban.schemas.events import ChangesOut, EventEntity, EventOut
from kanban.schemas.labels import (
    CardLabelsOut,
    LabelCreateIn,
    LabelOut,
    LabelsOut,
    LabelUpdateIn,
)
from kanban.schemas.lists import (
    ArchiveAllCardsOut,
    ListCopyIn,
    ListCreateIn,
    ListMoveIn,
    ListOut,
    ListSortIn,
    ListsOut,
    ListUpdateIn,
    ListWithCountOut,
    MoveAllCardsIn,
    MoveAllCardsOut,
    PositionsOut,
    UnarchiveCardsIn,
    UnarchiveCardsOut,
)
from kanban.schemas.members import CardMembersOut, WatchOut
from kanban.schemas.search import SearchBoard, SearchCard, SearchCardLabel, SearchResults

__all__ = [
    "ActivityFeedItem",
    "ActivityOut",
    "ActivityPage",
    "ArchiveAllCardsOut",
    "ArchivedCardsPage",
    "ArchivedListsPage",
    "AttachmentCreateIn",
    "AttachmentMutated",
    "AttachmentOut",
    "AttachmentUpdateIn",
    "BackgroundColorOut",
    "BackgroundGradientOut",
    "BoardActivityOut",
    "BoardBackgroundOut",
    "BoardChecklistOut",
    "BoardChecklistsOut",
    "BoardCreateIn",
    "BoardGroups",
    "BoardOut",
    "BoardSummary",
    "BoardUpdateIn",
    "CardBadges",
    "CardCopyIn",
    "CardCover",
    "CardCreateIn",
    "CardDetail",
    "CardFeedOut",
    "CardKeepIn",
    "CardLabelsOut",
    "CardMembersOut",
    "CardMoveIn",
    "CardMoveResult",
    "CardMutated",
    "CardSummary",
    "CardUpdateIn",
    "CardsCreated",
    "ChangesOut",
    "ChecklistCreateIn",
    "ChecklistItemOut",
    "ChecklistItemPatchedOut",
    "ChecklistMoveResult",
    "ChecklistMutated",
    "ChecklistOut",
    "ChecklistUpdateIn",
    "ClosedBoardGroup",
    "CommentCreateIn",
    "CommentFeedItem",
    "CommentMutated",
    "CommentOut",
    "CommentUpdateIn",
    "CoverIn",
    "CoverKind",
    "CoverSize",
    "CustomBackgroundOut",
    "DevLoginIn",
    "ErrorBody",
    "ErrorEnvelope",
    "EventEntity",
    "EventOut",
    "FeedItemOut",
    "Health",
    "ItemConvertIn",
    "ItemCreateIn",
    "ItemMoveIn",
    "ItemMoveResult",
    "ItemMutated",
    "ItemPatched",
    "ItemUpdateIn",
    "ItemsCreated",
    "LabelColorOut",
    "LabelCreateIn",
    "LabelOut",
    "LabelUpdateIn",
    "LabelsOut",
    "ListCopyIn",
    "ListCreateIn",
    "ListMoveIn",
    "ListOut",
    "ListSortIn",
    "ListUpdateIn",
    "ListWithCountOut",
    "ListsOut",
    "LoginIn",
    "MemberOut",
    "MemberRoleIn",
    "MembersOut",
    "Meta",
    "MoveAllCardsIn",
    "MoveAllCardsOut",
    "MoveIn",
    "MoveResult",
    "Mutated",
    "PositionsOut",
    "ProfileUpdateIn",
    "PublicUserOut",
    "RegisterIn",
    "SearchBoard",
    "SearchCard",
    "SearchCardLabel",
    "SearchResults",
    "SessionOut",
    "StarOut",
    "UnarchiveCardsIn",
    "UnarchiveCardsOut",
    "UserListOut",
    "UserOut",
    "WatchOut",
]
