"""Pydantic request/response models, one module per domain, re-exported here.

The plan lists a single `schemas.py`; it is a package so each domain keeps its own module while
every documented import path (`from kanban.schemas import MoveIn`) still resolves. See CLAUDE.md
section 8. The per-resource modules arrive with their routers, and every public model of each one
is re-exported here so callers never need to know which module declares it.
"""

from kanban.schemas.activity import ActivityOut, ActivityPage, BoardActivityOut
from kanban.schemas.archived import ArchivedCardsPage, ArchivedListsPage
from kanban.schemas.boards import (
    BackgroundColorOut,
    BackgroundGradientOut,
    BoardBackgroundOut,
    BoardCreateIn,
    BoardGroups,
    BoardOut,
    BoardSummary,
    BoardUpdateIn,
    ClosedBoardGroup,
    CustomBackgroundOut,
)
from kanban.schemas.cards import (
    CardCreateIn,
    CardDetail,
    CardMoveIn,
    CardMoveResult,
    CardMutated,
    CardsCreated,
    CardSummary,
    CardUpdateIn,
)
from kanban.schemas.common import (
    CardBadges,
    ErrorBody,
    ErrorEnvelope,
    Health,
    LabelColorOut,
    Meta,
    MoveIn,
    MoveResult,
    Mutated,
)
from kanban.schemas.events import ChangesOut, EventEntity, EventOut
from kanban.schemas.items import (
    CardItemOut,
    CardItemPatchedOut,
    ItemCreateIn,
    ItemMoveIn,
    ItemMoveResult,
    ItemMutated,
    ItemPatched,
    ItemsCreated,
    ItemUpdateIn,
)
from kanban.schemas.labels import (
    CardLabelsOut,
    LabelCreateIn,
    LabelOut,
    LabelsOut,
    LabelUpdateIn,
)
from kanban.schemas.lists import (
    ArchiveAllCardsOut,
    ListCopyIn,
    ListCreateIn,
    ListMoveIn,
    ListOut,
    ListSortIn,
    ListsOut,
    ListUpdateIn,
    ListWithCountOut,
    MoveAllCardsIn,
    MoveAllCardsOut,
    PositionsOut,
    UnarchiveCardsIn,
    UnarchiveCardsOut,
)
from kanban.schemas.search import SearchBoard, SearchCard, SearchCardLabel, SearchResults

__all__ = [
    "ActivityOut",
    "ActivityPage",
    "ArchiveAllCardsOut",
    "ArchivedCardsPage",
    "ArchivedListsPage",
    "BackgroundColorOut",
    "BackgroundGradientOut",
    "BoardActivityOut",
    "BoardBackgroundOut",
    "BoardCreateIn",
    "BoardGroups",
    "BoardOut",
    "BoardSummary",
    "BoardUpdateIn",
    "CardBadges",
    "CardCreateIn",
    "CardDetail",
    "CardItemOut",
    "CardItemPatchedOut",
    "CardLabelsOut",
    "CardMoveIn",
    "CardMoveResult",
    "CardMutated",
    "CardSummary",
    "CardUpdateIn",
    "CardsCreated",
    "ChangesOut",
    "ClosedBoardGroup",
    "CustomBackgroundOut",
    "ErrorBody",
    "ErrorEnvelope",
    "EventEntity",
    "EventOut",
    "Health",
    "ItemCreateIn",
    "ItemMoveIn",
    "ItemMoveResult",
    "ItemMutated",
    "ItemPatched",
    "ItemUpdateIn",
    "ItemsCreated",
    "LabelColorOut",
    "LabelCreateIn",
    "LabelOut",
    "LabelUpdateIn",
    "LabelsOut",
    "ListCopyIn",
    "ListCreateIn",
    "ListMoveIn",
    "ListOut",
    "ListSortIn",
    "ListUpdateIn",
    "ListWithCountOut",
    "ListsOut",
    "Meta",
    "MoveAllCardsIn",
    "MoveAllCardsOut",
    "MoveIn",
    "MoveResult",
    "Mutated",
    "PositionsOut",
    "SearchBoard",
    "SearchCard",
    "SearchCardLabel",
    "SearchResults",
    "UnarchiveCardsIn",
    "UnarchiveCardsOut",
]
